---
- name: Debug
  hosts: worker
  become: false
  tasks:
    - name: Show distribution
      debug: msg="{{ ansible_distribution | lower }}"
    - name: Show distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Show distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"